#### 순환신경망 RNN
<hr>



In [88]:
import torch
import torch.nn as nn


In [89]:
input = torch.randn(1,3,10) # 입력 데이터 (배치크기, 시퀀스길이, 피쳐길이)
h0 = torch.randn(2,3,1) # 히든 초기값

rnn = nn.RNN(input_size=10, hidden_size=1, num_layers=2)
output, hn = rnn(input, h0)

print(output, hn)

tensor([[[-0.5182],
         [ 0.0756],
         [-0.8578]]], grad_fn=<StackBackward0>) tensor([[[-0.9872],
         [ 0.2346],
         [-0.9931]],

        [[-0.5182],
         [ 0.0756],
         [-0.8578]]], grad_fn=<StackBackward0>)


In [90]:
### 설계 : 다층 RNN, 총 2개
### 입력
### ------------------------

HIDDEN_SIZE = 1
NUM_LAYERS = 1
SEQ_LENGTH = 3
BATCH_SIZE = 1

BIDIRECTIONAL = False
MULTIPLYER = 2 if BIDIRECTIONAL else 1
## 배치사이즈, 시퀀스 (1개문장구성 단어수), 피쳐수(1개단어 표현하는 수)
user =  torch.randn(BATCH_SIZE, SEQ_LENGTH, 10)

## 층수 * 양방향, 배치사이즈, 아웃 히든 사이즈, [히든 스테이트 초기화]
h0 = torch.randn(MULTIPLYER * NUM_LAYERS, BATCH_SIZE, HIDDEN_SIZE)

# RNN 인스턴스
rnn = nn.RNN(10, HIDDEN_SIZE, NUM_LAYERS, bidirectional=BIDIRECTIONAL, batch_first=True)

# 출력 텐서들
output, hn = rnn(user, h0)


In [91]:
print(f"input data : {user.shape}, dim : {user.ndim}D")


input data : torch.Size([1, 3, 10]), dim : 3D


In [92]:
print(f" rnn 출력 : {hn.shape}, dim : {hn.ndim}D")
hn

 rnn 출력 : torch.Size([1, 1, 3]), dim : 3D


tensor([[[ 0.5506,  0.2746, -0.7051]]], grad_fn=<StackBackward0>)

In [93]:
for name, params in rnn.named_parameters():
    print(f"[name] : {name}, {params}")

[name] : weight_ih_l0, Parameter containing:
tensor([[-0.1576, -0.5539,  0.2259, -0.3247, -0.2661, -0.3457, -0.1584,  0.0563,
         -0.2150, -0.4387],
        [-0.0498, -0.5119, -0.3126,  0.3201, -0.0241, -0.5584, -0.0158, -0.1566,
         -0.1876, -0.3093],
        [-0.4976,  0.5599, -0.1196,  0.2324,  0.2207, -0.2485, -0.2081, -0.3814,
         -0.0022, -0.5723]], requires_grad=True)
[name] : weight_hh_l0, Parameter containing:
tensor([[-0.1633, -0.2360, -0.1283],
        [ 0.0616,  0.1061,  0.1337],
        [-0.0900,  0.1600,  0.0552]], requires_grad=True)
[name] : bias_ih_l0, Parameter containing:
tensor([-0.5041,  0.2481,  0.2385], requires_grad=True)
[name] : bias_hh_l0, Parameter containing:
tensor([-0.3431, -0.2271,  0.3775], requires_grad=True)


In [94]:

print(output.shape, hn.shape)

torch.Size([1, 3, 3]) torch.Size([1, 1, 3])


In [95]:
### rnn 모델의 속성 출력
print(f"[all_weights] : {rnn.all_weights.__len__()}개")
for weight in rnn.all_weights:
    print(f"[weight] : {weight.__len__()}개")
    for detailweight in weight:
        print(detailweight.__len__())

[all_weights] : 1개
[weight] : 4개
3
3
3
3


In [96]:
for name, param in rnn.named_parameters():
    print(f"[name] : {name}")
    print(f"[param] : {param.size()}")

[name] : weight_ih_l0
[param] : torch.Size([3, 10])
[name] : weight_hh_l0
[param] : torch.Size([3, 3])
[name] : bias_ih_l0
[param] : torch.Size([3])
[name] : bias_hh_l0
[param] : torch.Size([3])


In [97]:
from torchinfo import summary
summary(rnn)

Layer (type:depth-idx)                   Param #
RNN                                      45
Total params: 45
Trainable params: 45
Non-trainable params: 0

In [98]:
### RNN 출력 텐서 output
output.shape

torch.Size([1, 3, 3])

In [99]:
from torchviz import make_dot

make_dot(output, params=dict(list(rnn.named_parameters()))).render("rnn", format="png")

'rnn.png'

In [100]:
# !conda env export > environment.yaml